version: '3'
services:
  db:
    image: "postgres"
    environment:
      POSTGRES_USER: "h3lix"
      POSTGRES_DB: "theoryfall"
      POSTGRES_PASS: "hihi00hihi"
    ports:
      "5432:5432"
    restart: "always"
    volumes:
      "/var/lib/postgresql/data:/var/lib/postgresql/data"
  redis:
    image: "redis"
    ports:
      "6379:6379"
    restart: "always"