version: "3"
services:
  db:
    image: "postgres:latest"
    environment:
      POSTGRES_USER: "h3lix"
      POSTGRES_DB: "theoryfall"
      POSTGRES_PASSWORD: "hihi00hihi"
    ports:
      - "5432:5432"
    volumes:
      - "/var/lib/postgressql/data:/var/lib/postgressql/data"
      - "/bar/lib/postgressql/backups:/backups"
    restart: "always"
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    restart: "always"
